# Site Settings
lang: en
title: Evolv-ED 
tagline: Educating Computer-based Eco-Evolutionary Science
email: your-email@domain.com
description: >
  
baseurl: ""
url: "https://evolv-ed.net/"
# permalink: pretty
#favicon: /path/to/favicon.png
# gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
force_theme: light

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname:  


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from
  - jekyll-datapage-generator

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _material/

include: ['CNAME']

livereload: false 

sass:
  style: compressed
  source_dir: _sass
  # load_paths: 
    # - node_modules

#google_analytics: UA-code-here
cookie_policy: 

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false 
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      show_sidebar: false 

markdown: kramdown
highlighter: rouge

footer_menu: footer 

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

# the automatic page generator
page_gen-dirs: true
page_gen:
- data: 'tutorialversions'
  template: 'tutorials'
  dir: 'tutorials'
  index_files: false
  version: 'version'
  datum: 'datum'
  tutorial: 'tutorial'
  name_expr: record['tutorial'] + '-' + record['version']
  title: 'title'
  extension: 'html'
  dependencies: 'dependencies'
  topic: 'topic'
  tags: 'tags'
  files: 'files'
- data: 'software'
  template: 'software'
  dir: 'software'
  index_files: false
  name: 'id'
  id: 'id'
  longName: 'longName'
  display: 'display'
  extension: 'html'
  extends: 'extends'
- data: 'data'
  template: 'data'
  dir: 'data'
  index_files: false
  name: 'id'
  id: 'id'
  long: 'long'
  extension: 'html'
  logo: 'logo'
  website: 'website'
  taxonomic_scope: 'taxonomic_scope'
  temporal_scope: 'temporal_scope'
  spatial_scope: 'spatial_scope'
  since: 'since'
  license: 'license'
  abbreviation: 'abbreviation'
- data: 'data_categ'
  template: 'data_categ'
  dir: 'data'
  index_files: false
  title: 'long'
  name: 'id'
  long: 'long'
  image: 'image'
  description: 'description'
  subcategories: 'subcategories'
